import type { Metadata } from "next";
import { AppProvider } from "../context/AppContext";
import { Inter } from "next/font/google";
import "./globals.css";
import "./PDFForm.css";
import NavBar from "./components/NavBar";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Resume Builder",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppProvider>
          
          <NavBar />
          {children}
        </AppProvider>
      </body>
    </html>
  );
}
